### ISSUE TITLE
How can I actually get it to document the test?

### ISSUE THREAD

**Issue by knewter** [dantswain/ex_unit_api_documentation#1]
I'm trying this out at https://github.com/knewter/chatbot_dsl_api/tree/feature/add_ex_unit_api_documentation and I haven't been able to figure out how/when the `document` function gets called in ExUnitApiDocumentation.  I really like the integration testing style from your blog post in general btw.

Anyway, sorry to badger you, but I think the project is very cool and want to fiddle with it some! :)

**Comment by dantswain** [comment]
Hi Josh, no worries.  I got sidetracked from this project for a couple months, but I've been working on it a bit lately.

Right now the documentation is just dumped to a JSON file :/  I want to work on creating a simple viewer that you can mount in your app.  I'm not a javascript pro, though, so it's slow going.  Contributions are gratefully accepted, even if it's just testing ;)  I'll update this issue once I have something a little more concrete for you try.

**Comment by knewter** [comment]
I got an empty JSON file when I ran the tests.  I read through the code and
couldn't quite figure out why that was or how to fix it.  I want to get
this working and then try one of the existing rails-focused 'viewers' for
the json data.

On Tue, Aug 25, 2015 at 6:35 PM, Dan notifications@github.com wrote:

> Hi Josh, no worries. I got sidetracked from this project for a couple
> months, but I've been working on it a bit lately.
> 
> Right now the documentation is just dumped to a JSON file :/ I want to
> work on creating a simple viewer that you can mount in your app. I'm not a
> javascript pro, though, so it's slow going. Contributions are gratefully
> accepted, even if it's just testing ;) I'll update this issue once I have
> something a little more concrete for you try.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/dantswain/ex_unit_api_documentation/issues/1#issuecomment-134770674
> .

## 

_Josh Adams_
CTO | isotope|eleven http://www.isotope11.com
[cell](205) 215-3957
[work](877) 476-8671 x201

[mail]
3800 Colonnade Pkwy
Suite 140
Birmingham, AL 35242

**Comment by dantswain** [comment]
Hi @knewter, I've made some updates and, particularly, updated the documentation.  If you have time, could you give this another try?

I think the thing you were missing was the call to `ExUnitApiDocumentation.document` in your API helper.  Check out https://github.com/dantswain/ex_unit_api_documentation_test_app/blob/master/test/support/api.ex#L55-L59 for an example.

This is all still a little clunky for sure but it should at least work.  Let me know if you're able to get it to work!

**Comment by knewter** [comment]
Derp thanks, that totally works! :)  :+1:
